const List<Map<String, String>> allProducts = [
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 11_51_55 AM.png",
    "category": "RINGS",
    "name": "Minimalist Gold Drop",
    "price": "\$1,460",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 11_53_51 AM.png",
    "category": "RINGS",
    "name": "Signet du Paris",
    "price": "\$1,280",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 12_23_06 PM.png",
    "category": "WATCHES",
    "name": "Chronos Ivory I",
    "price": "\$8,600",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 11_50_14 AM.png",
    "category": "BRACELETS",
    "name": "Sculpture Cuff",
    "price": "\$3,200",
  },
  {
    "image": "IMAGES/CHAIN3.png",
    "category": "RINGS",
    "name": "The Pavé Band",
    "price": "\$13,500",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 11_33_59 AM.png",
    "category": "RINGS",
    "name": "Diamond Solitaire Studs",
    "price": "\$14,600",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 12_17_57 PM.png",
    "category": "NECKLACES",
    "name": "Heritage Link Bracelet",
    "price": "\$4,200",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 11_44_48 AM.png",
    "category": "NECKLACES",
    "name": "Heritage Link Bracelet",
    "price": "\$4,200",
  },

  {
    "image": "IMAGES/0b7736f6e0fccbaea56caff25688c2da.jpg",
    "category": "READY-TO-WEAR",
    "name": "Structured Wool Blazer",
    "price": "\$2,750",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/0718f052a163a4295664f03aa7b969f0.jpg",
    "category": "OUTERWEAR",
    "name": "Star-Worth Ivory Coat",
    "price": "\$4,100",
    "filter": "OUTERWEAR",
  },
  {
    "image":
        "IMAGES/Blackpink-Jennie-Chanel-goth-coquette-aesthetic-titkok-fashion-trend-2024-Paris-fashion-week-2-1-scaled.webp",
    "category": "READY-TO-WEAR",
    "name": "Ribbed Cashmere Turtleneck",
    "price": "\$890",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/May 21, 2026, 12_37_37 PM.png",
    "category": "READY-TO-WEAR",
    "name": "Wide-Leg Wool Trouser",
    "price": "\$1,200",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/S24_JENNIE_DIGI_PR_nologo_1080x1350_7.webp",
    "category": "READY-TO-WEAR",
    "name": "The Double Tote Bag",
    "price": "\$3,400",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/ChatGPT Image May 21, 2026, 12_43_40 PM.png",
    "category": "DRESSES",
    "name": "Sculptured Silk Blouse",
    "price": "\$1,560",
    "filter": "DRESSES",
  },
  {
    "image": "IMAGES/51g8y-xHoDL._AC_UF894,1000_QL80_.jpg",
    "category": "DRESSES",
    "name": "Lace Atelier Evening Gown",
    "price": "\$7,200",
    "filter": "DRESSES",
  },
  {
    "image": "IMAGES/jennie-2-1.jpg",
    "category": "DRESSES",
    "name": "Asymmetric Pleated Skirt",
    "price": "\$1,890",
    "filter": "DRESSES",
  },
  {
    "image": "IMAGES/jennie-pictures-am9k0lvwt763kfqa.jpg",
    "category": "DRESSES",
    "name": "Asymmetric Pleated Skirt",
    "price": "\$1,890",
    "filter": "DRESSES",
  },
  {
    "image": "IMAGES/jjjjjjjjjjjjjjjjjjjj.jpg",
    "category": "READY-TO-WEAR",
    "name": "Chanel Velvet Strapless Dress",
    "price": "\$7,100",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/jjjjjjjjjjjjjjjjj.webp",
    "category": "READY-TO-WEAR",
    "name": "Jacquemus La Robe Foulard Strapless Dress",
    "price": "\$1,120",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/jjjjjjjjjjjjjjjjjjjj.webp",
    "category": "READY-TO-WEAR",
    "name": "Calvin Klein Modern Cotton Bralette",
    "price": "\$4,8000",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/jjjjjjjjjjjjjjjjjj.webp",
    "category": "READY-TO-WEAR",
    "name": "Calvin Klein Denim Zip-Up Jacket",
    "price": "\$1,2800",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/jjjjjjjjjjj.jpg",
    "category": "READY-TO-WEAR",
    "name": "Lace Bustier & Wide-Leg Tweed Trousers",
    "price": "\$8,200",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/jjjjjjjj.jpg",
    "category": "READY-TO-WEAR",
    "name": "Classic Oversized Lambskin Leather Jacket",
    "price": "\$1,450",
    "filter": "READY-TO-WEAR",
  },
  {
    "image": "IMAGES/Luxury Watch.png",
    "category": "TIMEPIECE",
    "name": "The Chronos 01",
    "price": "\$4,200",
    "filter": "MEN",
  },
  {
    "image": "IMAGES/Leather Bag.png",
    "category": "LUGGAGE",
    "name": "Italian Leather Holdall",
    "price": "\$1,800",
    "filter": "MEN",
  },
  {
    "image": "IMAGES/Silk Scarf.png",
    "category": "TEXTILE",
    "name": "Heritage Cashmere Scarf",
    "price": "\$450",
    "filter": "MEN",
  },
  {
    "image": "IMAGES/0b7736f6e0fccbaea56caff25688c2da.jpg",
    "category": "READY-TO-WEAR",
    "name": "Structured Wool Blazer",
    "price": "\$2,750",
    "filter": "MEN",
  },
  {
    "image": "IMAGES/0718f052a163a4295664f03aa7b969f0.jpg",
    "category": "OUTERWEAR",
    "name": "Star-Worth Ivory Coat",
    "price": "\$4,100",
    "filter": "MEN",
  },
];
