// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByDJEfpFVSkW53t9dQMVvy1id-TU85Ijk',
    appId: '1:955366303571:web:4c87b62937a6fba0a2e3a6',
    messagingSenderId: '955366303571',
    projectId: 'e-commerce-d49d2',
    authDomain: 'e-commerce-d49d2.firebaseapp.com',
    storageBucket: 'e-commerce-d49d2.firebasestorage.app',
    measurementId: 'G-RP052VHD36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPBtOTa3aOFM7lLG0ZD4O-y7wyI2-VSE',
    appId: '1:955366303571:android:a2e443a06332259ba2e3a6',
    messagingSenderId: '955366303571',
    projectId: 'e-commerce-d49d2',
    storageBucket: 'e-commerce-d49d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqd4e022p9LvmqGo4K8nIPp2Vcxz3jhnI',
    appId: '1:955366303571:ios:b5fc37013e168345a2e3a6',
    messagingSenderId: '955366303571',
    projectId: 'e-commerce-d49d2',
    storageBucket: 'e-commerce-d49d2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceOpenfashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqd4e022p9LvmqGo4K8nIPp2Vcxz3jhnI',
    appId: '1:955366303571:ios:b5fc37013e168345a2e3a6',
    messagingSenderId: '955366303571',
    projectId: 'e-commerce-d49d2',
    storageBucket: 'e-commerce-d49d2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceOpenfashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByDJEfpFVSkW53t9dQMVvy1id-TU85Ijk',
    appId: '1:955366303571:web:6f3ddc191b3db325a2e3a6',
    messagingSenderId: '955366303571',
    projectId: 'e-commerce-d49d2',
    authDomain: 'e-commerce-d49d2.firebaseapp.com',
    storageBucket: 'e-commerce-d49d2.firebasestorage.app',
    measurementId: 'G-E33J6KTJ9J',
  );
}
